#!/bin/sh
#
# Copyright 2014-2016 CyberVision, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

platform=
if [ -f /virt_env ]; then
    platform="$(cat /virt_env)"
fi
		
if [ -e /etc/init.d/kaa_box_startup ]; then
    rm -f /etc/init.d/kaa_box_startup
fi

if [ -e /usr/lib/kaa-sandbox/startup.sh ]; then
    rm -f /usr/lib/kaa-sandbox/startup.sh
fi

if [ -h /etc/kaa-sandbox/conf ]; then
    rm -f /etc/kaa-sandbox/conf
fi

if [ ! -d /etc/kaa-sandbox ]; then
    mkdir -p /etc/kaa-sandbox
fi

if [ ! -d /var/log/kaa ]; then
    mkdir -p /var/log/kaa
fi

chown -R kaa:kaa /var/log/kaa
chmod 755 /var/log/kaa

if [ $platform = "vbox" ]; then
    ln -s /usr/lib/kaa-sandbox/bin/kaa_box_startup /etc/init.d/kaa_box_startup
    ln -s /usr/lib/kaa-sandbox/bin/startup.sh /usr/lib/kaa-sandbox/startup.sh
fi
        
ln -s /usr/lib/kaa-sandbox/conf /etc/kaa-sandbox/conf

if [ -f /usr/lib/kaa-sandbox/bin/kaa-sandbox.default ]; then
    cp -f /usr/lib/kaa-sandbox/bin/kaa-sandbox.default /etc/default/kaa-sandbox
fi

if [ -f /usr/lib/kaa-sandbox/bin/kaa-sandbox.init.d ]; then
    cp -f /usr/lib/kaa-sandbox/bin/kaa-sandbox.init.d /etc/init.d/kaa-sandbox
fi

if [ -x "/etc/init.d/kaa-sandbox" ]; then
	if [ ! -e "/etc/init/kaa-sandbox.conf" ]; then
		if ! chkconfig_loc="$(type -p "chkconfig")" || [ -z "$chkconfig_loc" ]; then
		    update-rc.d -f kaa-sandbox defaults >/dev/null
		else
		    chkconfig --add kaa-sandbox >/dev/null
		fi
	fi
fi

if [ $platform = "vbox" ] && [ -x "/etc/init.d/kaa_box_startup" ]; then
	    if ! chkconfig_loc="$(type -p "chkconfig")" || [ -z "$chkconfig_loc" ]; then
            update-rc.d -f kaa_box_startup remove >/dev/null || exit 1
            update-rc.d -f kaa_box_startup defaults 19 >/dev/null || exit 1
        else
            chkconfig --add kaa_box_startup >/dev/null || exit 1
        fi
fi
